
import Footer from "@/components/ui/Footer"
import "./globals.css"
import { Hero } from "@/components/ui/Header/Hero"

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
          {children}
          <Footer />
       </body>
    </html>
  )
}
