
import Footer from "@/components/ui/Footer"
import "./globals.css"
import { CartProvider } from "@/components/context/CartContext"
import { Authprovider } from "@/components/context/AuthContext"

export const metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Authprovider>
        <CartProvider>

          {children}

          <Footer />
          </CartProvider>
          </Authprovider>
       </body>
    </html>
  )
}
